---
name: linux-arm-gcc
on:
  push:
    paths:
      - .gitea/workflows/linux-arm-gcc.yml
      - toolchains/arm-linux-gnueabi.toolchain.cmake
      - toolchains/arm-linux-gnueabihf.toolchain.cmake
      - 3party/**
      - include/**
      - src/**
      - tests/**
      - CMakeLists.txt
      - cmake/**
  pull_request:
    paths:
      - .gitea/workflows/linux-arm-gcc.yml
      - toolchains/arm-linux-gnueabi.toolchain.cmake
      - toolchains/arm-linux-gnueabihf.toolchain.cmake
      - 3party/**
      - include/**
      - src/**
      - tests/**
      - CMakeLists.txt
      - cmake/**
concurrency:
  group: linux-arm-gcc-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # linux-gcc-arm:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: arm-gnu-toolchain
  #       run: |
  #         sudo apt-get update -y
  #         sudo apt-get install -y cmake make g++-arm-linux-gnueabi qemu-user-binfmt
  #     - name: build
  #       run: |
  #         mkdir build && cd build
  #         cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabi.toolchain.cmake -DSLED_BUILD_TESTS=ON -DSLED_BUILD_TESTS=ON ..
  #         cmake --build . -j $(nproc)
  #     - name: test
  #       run: |
  #         cd build
  #         ln -sf /usr/arm-linux-gnueabi/lib/ld-linux.so.3
  #         export LD_LIBRARY_PATH=/usr/arm-linux-gnueabi/lib
  #         qemu-arm ctest --output-on-failure -j$(nproc)
  linux-gcc-armhf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: arm-gnu-toolchain
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake make g++-arm-linux-gnueabihf qemu-user-binfmt
      - name: build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabihf.toolchain.cmake -DSLED_BUILD_TESTS=ON ..
          cmake --build . -j $(nproc)
      - name: test
        run: |-
          cd build
          ln -sf /usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3 /lib/ld-linux-armhf.so.3
          export LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib/
          ctest --output-on-failure -j$(nproc)
